
# Uncomment this line to define a global platform for your project
platform :ios, ‘8.0’
# Uncomment this line if you're using Swift
# use_frameworks!

# 开发环境库
def develop_pods
    pod '${POD_NAME}/Develop’, :path => '../'
end


target '${POD_NAME}' do

  develop_pods

  target '${POD_NAME}_Tests' do
    inherit! :search_paths
  end
end
